#pragma once
UENUM(BlueprintType)
enum class EGalaxyClass : uint8
{
	E0			UMETA(DisplayName = "E0 Elliptical"),
	E1			UMETA(DisplayName = "E1 Elliptical"),
	E2			UMETA(DisplayName = "E2 Elliptical"),
	E3			UMETA(DisplayName = "E3 Elliptical"),
	E4			UMETA(DisplayName = "E4 Elliptical"),
	E5			UMETA(DisplayName = "E5 Elliptical"),
	E6			UMETA(DisplayName = "E6 Elliptical"),
	E7			UMETA(DisplayName = "E7 Elliptical"),
	S0			UMETA(DisplayName = "S0 Lenticular"),
	// Sa..SBd keep their historic output (arm count only) for saved worlds; the menu
	// offers the per-type subclasses appended below instead (Rio 03.10).
	Sa			UMETA(DisplayName = "Sa Spiral (legacy)"),
	Sb			UMETA(DisplayName = "Sb Spiral (legacy)"),
	Sc			UMETA(DisplayName = "Sc Spiral (legacy)"),
	Sd			UMETA(DisplayName = "Sd Spiral (legacy)"),
	SBa			UMETA(DisplayName = "SBa Barred Spiral (legacy)"),
	SBb			UMETA(DisplayName = "SBb Barred Spiral (legacy)"),
	SBc			UMETA(DisplayName = "SBc Barred Spiral (legacy)"),
	SBd			UMETA(DisplayName = "SBd Barred Spiral (legacy)"),
	Irr			UMETA(DisplayName = "Irr Irregular"),
	Unknown		UMETA(DisplayName = "Unknown"),
	// Rio 03.10: per-type subclasses (APSGalaxyMorphology). Appended after Unknown so every
	// serialized name and byte above is unchanged. Never reorder or rename these values.
	SpiralSa		UMETA(DisplayName = "Sa Spiral"),
	SpiralSab		UMETA(DisplayName = "Sab Spiral"),
	SpiralSb		UMETA(DisplayName = "Sb Spiral"),
	SpiralSbc		UMETA(DisplayName = "Sbc Spiral"),
	SpiralSc		UMETA(DisplayName = "Sc Spiral"),
	SpiralScd		UMETA(DisplayName = "Scd Spiral"),
	SpiralSd		UMETA(DisplayName = "Sd Spiral"),
	SpiralSm		UMETA(DisplayName = "Sm Magellanic Spiral"),
	BarredSBa		UMETA(DisplayName = "SBa Barred Spiral"),
	BarredSBab		UMETA(DisplayName = "SBab Barred Spiral"),
	BarredSBb		UMETA(DisplayName = "SBb Barred Spiral"),
	BarredSBbc		UMETA(DisplayName = "SBbc Barred Spiral"),
	BarredSBc		UMETA(DisplayName = "SBc Barred Spiral"),
	BarredSBcd		UMETA(DisplayName = "SBcd Barred Spiral"),
	BarredSBd		UMETA(DisplayName = "SBd Barred Spiral"),
	BarredSBm		UMETA(DisplayName = "SBm Barred Magellanic"),
	SB0				UMETA(DisplayName = "SB0 Barred Lenticular"),
	S0a				UMETA(DisplayName = "S0/a Lenticular"),
	cD				UMETA(DisplayName = "cD Supergiant Elliptical"),
	dE				UMETA(DisplayName = "dE Dwarf Elliptical"),
	Im				UMETA(DisplayName = "Im Magellanic Irregular"),
	IBm				UMETA(DisplayName = "IBm Barred Irregular"),
	dIrr			UMETA(DisplayName = "dIrr Dwarf Irregular"),
	I0				UMETA(DisplayName = "I0 Starburst Irregular"),
	PecWarped		UMETA(DisplayName = "Pec Warped Disk"),
	PecRing			UMETA(DisplayName = "Pec Ring Galaxy"),
	PecInteracting	UMETA(DisplayName = "Pec Interacting Pair"),
	PecTidalTails	UMETA(DisplayName = "Pec Tidal Tails"),
	PecPolarRing	UMETA(DisplayName = "Pec Polar Ring"),
};